import re
from typing import TypedDict, Optional
from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver

load_dotenv()

# 1. Define State (Tracks the conversational stages, form slots, and resolutions)
class ReturnState(TypedDict):
    user_message: str
    order_id: Optional[str]
    return_reason: Optional[str]
    system_instruction: str                  # Instructions back to the user
    proposal: Optional[str]                  # Proposed resolution generated by LLM
    flow_stage: str                         # "collecting_info", "proposed", "resolved"
    customer_decision: Optional[str]         # "accepted" or "rejected"
    resolution_message: Optional[str]        # Final processed refund/escalation details

# Initialize LLM
llm = ChatGoogleGenerativeAI(model="gemini-flash-lite-latest")

# ==========================================
# NODE 1: Deterministic Python Validator
# ==========================================
def deterministic_validator(state: ReturnState):
    print("⚙️ [Deterministic Node] Checking form slots...")
    
    stage = state.get("flow_stage", "collecting_info")
    if stage == "resolved":
        return {
            "system_instruction": "Your return request has already been resolved. Please reset the chat or start a new thread if you have another query."
        }
    if stage == "proposed":
        # Do not modify slots when in "proposed" stage
        return {}
        
    current_message = state.get("user_message", "")
    order_id = state.get("order_id")
    reason = state.get("return_reason")
    
    # 1. Try to extract a 6-digit Order ID (e.g., #123456 or 123456)
    if not order_id:
        match = re.search(r"\b#?(\d{6})\b", current_message)
        if match:
            order_id = match.group(1)
            print(f"   ↳ Extracted Order ID: {order_id}")
            
    # 2. Try to extract a reason (looking for keywords: damaged, size, wrong, other)
    if not reason:
        text_lower = current_message.lower()
        if "damage" in text_lower or "broken" in text_lower or "defect" in text_lower:
            reason = "Damaged Item"
        elif "size" in text_lower or "fit" in text_lower or "tight" in text_lower or "loose" in text_lower:
            reason = "Incorrect Size"
        elif "wrong" in text_lower or "different" in text_lower or "mistake" in text_lower:
            reason = "Wrong Item Shipped"
        elif "other" in text_lower:
            reason = "Other"
            
    # 3. Formulate system response if info is missing
    if not order_id and not reason:
        instruction = "Welcome! To process your return, please provide your 6-digit Order ID and tell us why you are returning the item."
    elif not order_id:
        instruction = f"Thank you for the reason ({reason}). Could you please provide your 6-digit Order ID?"
    elif not reason:
        instruction = f"Got your order ID #{order_id}. Can you tell us why you are returning the item? (e.g., Damaged, Incorrect Size, Wrong Item)"
    else:
        instruction = "Form complete. Handing over to agent..."

    return {
        "order_id": order_id,
        "return_reason": reason,
        "system_instruction": instruction,
        "flow_stage": "collecting_info"
    }

# ==========================================
# NODE 2: Agentic LLM Proposer
# ==========================================
def agentic_proposer(state: ReturnState):
    print("🤖 [Agentic Node] Drafting return proposal with LLM...")
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are an empathetic customer support agent. The customer wants to return an item. "
                   "Based on their order details and return reason, propose a friendly and personalized solution. "
                   "For example, if the item was damaged or wrong, propose a replacement or full refund. "
                   "If the size was incorrect, propose an exchange for a different size. "
                   "Include a 15% discount code (RECOVER15) to win them back. "
                   "Explicitly ask the customer if they are okay with this proposed solution (e.g. 'Would you like me to go ahead and process this refund for you?'). "
                   "Keep your response natural, short, and conversational (1-2 paragraphs max). Do not write email headers or signatures, talk directly in chat."),
        ("user", "Order ID: #{order_id}\nReason for return: {return_reason}")
    ])
    
    chain = prompt | llm
    response = chain.invoke({
        "order_id": state["order_id"],
        "return_reason": state["return_reason"]
    })
    
    content = ""
    if isinstance(response.content, str):
        content = response.content
    elif isinstance(response.content, list):
        for part in response.content:
            if isinstance(part, dict) and part.get("type") == "text":
                content += part.get("text", "")
            elif isinstance(part, str):
                content += part
                
    return {
        "proposal": content,
        "flow_stage": "proposed"
    }

# ==========================================
# NODE 3: Agentic LLM Intent Classifier
# ==========================================
def decision_handler(state: ReturnState):
    print("🤖 [Agentic Node] Classifying customer decision...")
    prompt = ChatPromptTemplate.from_messages([
        ("system", "Analyze the user's message and determine if they agree/accept the proposed solution. "
                   "Respond with exactly one word: 'accepted' or 'rejected'. "
                   "If they say yes, sure, okay, that works, sounds good, please do, etc., classify as 'accepted'. "
                   "If they say no, want a human, want to talk to support, reject it, want something else, classify as 'rejected'."),
        ("user", "{user_message}")
    ])
    chain = prompt | llm
    response = chain.invoke({"user_message": state.get("user_message", "")})
    
    content = ""
    if isinstance(response.content, str):
        content = response.content
    elif isinstance(response.content, list):
        for part in response.content:
            if isinstance(part, dict) and part.get("type") == "text":
                content += part.get("text", "")
            elif isinstance(part, str):
                content += part

    decision = content.strip().lower()
    
    if "accepted" in decision:
        decision_val = "accepted"
    else:
        decision_val = "rejected"
        
    return {"customer_decision": decision_val}

# ==========================================
# NODE 4: Deterministic Refund Executor
# ==========================================
def process_refund(state: ReturnState):
    print("⚙️ [Deterministic Node] Processing refund...")
    order_id = state.get("order_id")
    return {
        "resolution_message": f"✅ **Refund Approved & Processed!** A full refund for Order #{order_id} has been successfully initiated. You should see the credit in your account in 3-5 business days.",
        "flow_stage": "resolved"
    }

# ==========================================
# NODE 5: Deterministic Escalation Executor
# ==========================================
def escalate_to_human(state: ReturnState):
    print("⚙️ [Deterministic Node] Escalating to human support...")
    order_id = state.get("order_id")
    reason = state.get("return_reason")
    return {
        "resolution_message": f"📧 **Support Ticket Created!** We have escalated Order #{order_id} (Reason: {reason}) to our human support team. A representative will contact you via email shortly.",
        "flow_stage": "resolved"
    }

# ==========================================
# ROUTING EDGES
# ==========================================
def route_next(state: ReturnState):
    stage = state.get("flow_stage", "collecting_info")
    if stage == "proposed":
        return "agentic_decision_handler"
    
    order_id = state.get("order_id")
    reason = state.get("return_reason")
    
    if order_id and reason:
        if stage == "resolved":
            return END
        if reason == "Other":
            return "deterministic_escalate"
        return "agentic_proposer"
    return END

def route_decision(state: ReturnState):
    decision = state.get("customer_decision")
    if decision == "accepted":
        return "deterministic_refund"
    return "deterministic_escalate"

# ==========================================
# BUILD THE GRAPH
# ==========================================
builder = StateGraph(ReturnState)

builder.add_node("deterministic_validator", deterministic_validator)
builder.add_node("agentic_proposer", agentic_proposer)
builder.add_node("agentic_decision_handler", decision_handler)
builder.add_node("deterministic_refund", process_refund)
builder.add_node("deterministic_escalate", escalate_to_human)

builder.add_edge(START, "deterministic_validator")

builder.add_conditional_edges(
    "deterministic_validator",
    route_next,
    {
        "agentic_proposer": "agentic_proposer",
        "agentic_decision_handler": "agentic_decision_handler",
        "deterministic_escalate": "deterministic_escalate",
        END: END
    }
)

builder.add_edge("agentic_proposer", END)

builder.add_conditional_edges(
    "agentic_decision_handler",
    route_decision,
    {
        "deterministic_refund": "deterministic_refund",
        "deterministic_escalate": "deterministic_escalate"
    }
)

builder.add_edge("deterministic_refund", END)
builder.add_edge("deterministic_escalate", END)

memory = MemorySaver()
graph = builder.compile(checkpointer=memory)

def stream(text: str, thread_id: str):
    config = {"configurable": {"thread_id": thread_id}}
    for chunk in graph.stream(
        {"user_message": text},
        config=config,
        stream_mode="updates"
    ):
        yield chunk

def get_state(thread_id: str):
    config = {"configurable": {"thread_id": thread_id}}
    state = graph.get_state(config)
    return state.values if state else {}

def clear_state(thread_id: str):
    config = {"configurable": {"thread_id": thread_id}}
    graph.update_state(config, {
        "order_id": None,
        "return_reason": None,
        "proposal": None,
        "flow_stage": "collecting_info",
        "customer_decision": None,
        "resolution_message": None,
        "user_message": "",
        "system_instruction": ""
    })


def save_graph_png():
    graph.get_graph().draw_mermaid_png(output_file_path="graph.png")

if __name__ == '__main__':
    save_graph_png()